//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZachetAcademyApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Evaluation = new HashSet<Evaluation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdSpecialization { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int IdTrainingForm { get; set; }
        public int IdGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluation { get; set; }
        public virtual Group Group { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual TrainingForm TrainingForm { get; set; }
    }
}
