//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZachetAcademyApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Evaluation = new HashSet<Evaluation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdSpecialization { get; set; }
        public int Year { get; set; }
        public int IdTrainingForm { get; set; }
        public int IdGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluation { get; set; }
        public virtual Group Group { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual TrainingForm TrainingForm { get; set; }
    }
}
